
export const documentGenres =
    [
        "Novel",
        "Short Story",
        "Poetry",
        "Drama",
        "Science Fiction",
        "Fantasy",
        "Horror",
        "Mystery",
        "Romance",
        "Adventure",
        "Humor",
        "Historical",
        "Detective",
        "Western",
        "Dystopian",
        "Realistic",
        "Juvenile",
        "Children's",
        "History",
        "Biography",
        "Business",
        "Politics",
        "Travel",
        "Gastronomy",
        "Art",
        "Photography",
        "Sports",
        "Education",
        "Science",
        "Technology",
        "Religion",
        "Environment",
        "Philosophy",
        "Sociology",
        "Journalism"
    ]